# Numpy

### 用dtype自定义数据类型

In [5]:
# 用dtype自定义数据类型
import numpy as np
dt = np.dtype([('name', np.str_, 40), ('num_array', np.float32, (3, 3))]) #这里40是字符串长度，3*3是数组维度
np = np.array([('hello', [1, 2, 3]), ('world', [4, 5, 6])], dtype=dt)
print(np)


[('hello', [[1., 2., 3.], [1., 2., 3.], [1., 2., 3.]])
 ('world', [[4., 5., 6.], [4., 5., 6.], [4., 5., 6.]])]


### 标准数组和对象数组

In [3]:
# 标准数组和对象数组
import numpy as np

# 每行长度相同
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print(arr.shape)  # 输出: (2, 3)

arr = np.array([[1, 2, 3], [4, 5]], dtype=object) #如果没有dtype会报错
print(arr)
print(arr.dtype)  # 输出: object
print(arr.shape)  # 输出: (2,)



[[1 2 3]
 [4 5 6]]
(2, 3)
[list([1, 2, 3]) list([4, 5])]
object
(2,)


### 高级索引

#### 整数数组索引

In [5]:
# 整数数组索引
import numpy as np 
#按位置进行索引，每个位置的索引放在不同数组；
x = np.array([[1,  2],  [3,  4],  [5,  6]]) 
y = x[[0,1,2],  [0,1,0]]  
print (y)


[1 4 5]


In [3]:
# 通过整数数组的形状控制输出的形状
import numpy as np
x = np.array([[1,  2],  [3,  4],  [5,  6]]) 
row = np.array([[1,2],[1,2]])
col = np.array([[1,0],[1,0]])
print(x[row, col])


[[4 5]
 [4 5]]


In [2]:
# 整数索引结合切片索引: 注意维度的变化，注意能不能取到
import numpy as np
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
b=a[1:3, 1:3]
c=a[[1,2], [1,2]] #c是1维数组
d=a[1:3, [1,2]]
e=a[[1,2], 1:3]
f=a[...,1:]
print("b是\n",b)
print("c是\n",c)
print("d是\n",d)
print("e是\n",e)
print("f是\n",f)


b是
 [[5 6]
 [8 9]]
c是
 [5 9]
d是
 [[5 6]
 [8 9]]
e是
 [[5 6]
 [8 9]]
f是
 [[2 3]
 [5 6]
 [8 9]]


#### 布尔索引

In [10]:
# 布尔索引
import numpy as np 
 
x = np.array([[  0,  1,  2],[  3,  4,  5],[  6,  7,  8],[  9,  10,  11]])  
print ('我们的数组是：')
print (x)
print ('\n')
# 现在我们会打印出大于 5 的元素
print("x>5的输出是：")  
print(x>5)
print("\n")
print  ('大于 5 的元素是：')
print (x[x >  5]) #可以看到输入是Ture和False，输出是True对应的元素；输出是1维数组；


我们的数组是：
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


x>5的输出是：
[[False False False]
 [False False False]
 [ True  True  True]
 [ True  True  True]]


大于 5 的元素是：
[ 6  7  8  9 10 11]


#### 花式索引

In [ ]:
# 多个索引数组
import numpy as np 
 
x=np.arange(32).reshape((8,4))
print (x[np.ix_([1,5,7,2],[0,3,1,2])])

### 数组迭代

### 数组操作