## Scipy笔记

### 稀疏矩阵
scipy.sparse 提供了多种稀疏矩阵格式和操作方法，常见的稀疏矩阵格式包括：
- CSR (Compressed Sparse Row)：行压缩稀疏矩阵格式
- CSC (Compressed Sparse Column)：列压缩稀疏矩阵格式
- COO (Coordinate)：坐标格式，适用于矩阵构建
- LIL (List of Lists)：行列表格式，适用于增量添加
- DOK (Dictionary of Keys)：字典格式，适用于动态修改矩阵

#### DOK矩阵
- DOK 是 Dictionary Of Keys（键的字典）的缩写。
- 它是一种稀疏矩阵格式，用字典来存储非零元素，字典的键是矩阵中的 (行索引, 列索引)，值是对应位置的元素值。
- 适合矩阵的构建与修改，不适合矩阵计算

##### 矩阵构建与修改

In [1]:
import scipy.sparse as sp

dok_matrix = sp.dok_matrix((5, 5)) 

dok_matrix[0, 0] = 1


##### 从numpy数组创建稀疏矩阵

In [4]:
import numpy as np
import scipy.sparse as sp

dense_matrix = np.array([[1, 0, 3], [0, 0, 0], [2, 0, 4]])
dok = sp.dok_matrix(dense_matrix)

print(dok)

dok[0, 0] = 0
print(f"修改值后：\n{dok}")


  (0, 0)	1
  (0, 2)	3
  (2, 0)	2
  (2, 2)	4
修改值后：
  (0, 2)	3
  (2, 0)	2
  (2, 2)	4


##### 从DOK转为numpy数组

In [5]:
import numpy as np
import scipy.sparse as sp

dense_matrix = np.array([[1, 0, 3], [0, 0, 0], [2, 0, 4]])
dok = sp.dok_matrix(dense_matrix)
numpy = dok.toarray()
print(f"numpy:\n{numpy}")

numpy:
[[1 0 3]
 [0 0 0]
 [2 0 4]]


##### 遍历所有数组元素

In [6]:
import numpy as np
import scipy.sparse as sp

dense_matrix = np.array([[1, 0, 3], [0, 0, 0], [2, 0, 4]])
dok = sp.dok_matrix(dense_matrix)

# 遍历非零元素
for (row, col), value in dok.items():
    print(f"位置 ({row}, {col}): {value}")

位置 (0, 0): 1
位置 (0, 2): 3
位置 (2, 0): 2
位置 (2, 2): 4


##### 从DOK矩阵转换为其他格式

In [8]:
import numpy as np
import scipy.sparse as sp

dense_matrix = np.array([[1, 0, 3], [0, 0, 0], [2, 0, 4]])
dok = sp.dok_matrix(dense_matrix)

csr = dok.tocsr()
print(f"csr:\n{csr}")
csc = dok.tocsc()
print(f"csc:\n{csc}")
coo = dok.tocoo()
print(f"coo:\n{coo}")

csr:
  (0, 0)	1
  (0, 2)	3
  (2, 0)	2
  (2, 2)	4
csc:
  (0, 0)	1
  (2, 0)	2
  (0, 2)	3
  (2, 2)	4
coo:
  (0, 0)	1
  (0, 2)	3
  (2, 0)	2
  (2, 2)	4


#### CSR矩阵

压缩稀疏行矩阵（CSR)，有三个核心元素：
- data：所有非零元素的值
- indices：每个非零元素对应的列索引
- indptr：每一行开始非零数据在 data 和 indices 中的起始位置


##### 矩阵构建与修改
法一：从numpy数组构建  
法二：从data,indices,indptr构建  
法三：按coo格式构建

In [4]:
import numpy as np
from scipy.sparse import csr_matrix

# 从numpy数组构建
dense = np.array([[0, 0, 1], [1, 0, 0], [0, 2, 0]])
sparse1 = csr_matrix(dense)
print(f"sparse1:\n{sparse1}")

# 从data,indices,indptr构建
data = np.array([1, 1, 2])
indices = np.array([2, 0, 1])
indptr = np.array([0, 1, 2, 3])
sparse2 = csr_matrix((data, indices, indptr), shape=(3, 3))

# 按coo格式构建
data = np.array([1, 1, 2])
row = np.array([0, 1, 2])
col = np.array([2, 0, 1])
sparse3 = csr_matrix((data, (row, col)), shape=(3, 3))

sparse1 == sparse2 

sparse1:
  (0, 2)	1
  (1, 0)	1
  (2, 1)	2


a:\program files\anaconda3\envs\pytorch\lib\site-packages\IPython\core\interactiveshell.py:3550: SparseEfficiencyWarning: Comparing sparse matrices using == is inefficient, try using != instead.
  exec(code_obj, self.user_global_ns, self.user_ns)


<3x3 sparse matrix of type '<class 'numpy.bool_'>'
	with 9 stored elements in Compressed Sparse Row format>