### Tensor操作

#### 转化为其它数据类型：
- 如果是标量，使用.item()可转化；
- 如果是向量，先使用.numpy()

### Tensor 代数

#### 创建矩阵
- 创建单位阵： torch.eye(n)
- 创建上三角阵： torch.triu(input, diagonal=0) (triangular upper)， 
  - input是另一个张量，不能只输入形状；
  - diagonal=0表示对角线为0，diagonal=1表示从对角线上一行开始，diagonal=-1表示从对角线下一行开始；
  - 上部值为1，下部值为0；
- 创建下三角阵： torch.tril(input, diagonal=0) (triangular lower)
- 创建对角阵：torch.diag(input, diagonal=0)
    - input如果是向量，则创建对角阵，如果是二维矩阵则返回对角线，不支持高维


In [1]:
import torch

v = torch.tensor([1, 2, 3, 4])  # 一维张量
D = torch.diag(v)
print(D)

M = torch.tensor([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
d = torch.diag(M)
print(d)

tensor([[1, 0, 0, 0],
        [0, 2, 0, 0],
        [0, 0, 3, 0],
        [0, 0, 0, 4]])
tensor([1, 5, 9])


#### 一些函数

##### torch.tensordot()

In [5]:
import torch

# 创建两个张量
a = torch.tensor([[1, 2], 
                [3, 4]])
b = torch.tensor([[5, 6], 
                [7, 8]])

# 在最后一个维度上进行点积; 只指定一个维度时是第一个张量的后n个维度与第二个张量的前n个维度做内积
result = torch.tensordot(a, b, dims=1) 
print(result)

tensor([[19, 22],
        [43, 50]])


In [6]:
# 二维矩阵在最后维度上的点积
a = torch.tensor([[1, 2],
                  [3, 4]])
b = torch.tensor([[5, 6],
                  [7, 8]])
c = torch.tensordot(a, b, dims=1)
print("\n二维矩阵在最后维度上的点积:")
print(c)
# 输出:
# tensor([[17, 23],
#         [39, 53]])

# 详细计算过程:
# c[0,0] = a[0,:]·b[0,:] = (1*5 + 2*7) = 17
# c[0,1] = a[0,:]·b[1,:] = (1*6 + 2*8) = 23
# c[1,0] = a[1,:]·b[0,:] = (3*5 + 4*7) = 39
# c[1,1] = a[1,:]·b[1,:] = (3*6 + 4*8) = 53


二维矩阵在最后维度上的点积:
tensor([[19, 22],
        [43, 50]])


In [13]:
import torch
a = torch.arange(24).reshape(2, 3, 4)  # shape: (2,3,4)
b = torch.arange(24).reshape(3, 2, 4)  # shape: (3,2,4)

print(a)
print(b)
# 在指定维度上进行张量点积
# dims=([1],[0]) 表示a的第1维(大小为3)和b的第0维(大小为3)进行收缩
result = torch.tensordot(a, b, dims=([1],[0]))
print(result)
print(result.shape)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7]],

        [[ 8,  9, 10, 11],
         [12, 13, 14, 15]],

        [[16, 17, 18, 19],
         [20, 21, 22, 23]]])
tensor([[[[160, 172, 184, 196],
          [208, 220, 232, 244]],

         [[184, 199, 214, 229],
          [244, 259, 274, 289]],

         [[208, 226, 244, 262],
          [280, 298, 316, 334]],

         [[232, 253, 274, 295],
          [316, 337, 358, 379]]],


        [[[448, 496, 544, 592],
          [640, 688, 736, 784]],

         [[472, 523, 574, 625],
          [676, 727, 778, 829]],

         [[496, 550, 604, 658],
          [712, 766, 820, 874]],

         [[520, 577, 634, 691],
          [748, 805, 862, 919]]]])
torch.Size([2, 4, 2, 4])


In [4]:
a = torch.randn(2, 3, 4)
b = torch.randn(2, 4, 3)
print(f"a 张量\n:{a}")
print(f"b 张量\n:{b}")
# 指定a的第0和2维，b的第0和1维收缩
result = torch.tensordot(a, b, dims=([0, 2], [0, 1]))
print(f"result 张量\n:{result}")
print(result.shape)  # torch.Size([3, 3])

a 张量
:tensor([[[ 0.3984,  0.3069, -1.0578,  0.7269],
         [ 0.2161,  0.7968,  1.0643,  1.4901],
         [-0.5727,  2.4418,  0.1298,  0.4969]],

        [[-0.1357, -0.1951,  0.7969, -0.2274],
         [ 0.0797,  1.1234, -0.1277,  2.3351],
         [-1.4290, -0.6711, -1.5325, -0.7372]]])
b 张量
:tensor([[[-0.1563, -1.4337, -0.1802],
         [ 0.4768, -1.4177, -0.0887],
         [-0.2966, -1.0002, -1.5477],
         [ 1.4982,  2.5524, -0.9826]],

        [[ 0.7916,  0.1740,  0.0315],
         [-2.0614,  0.0284, -0.9232],
         [ 1.0376,  0.4370, -0.3258],
         [-0.3902, -0.0320, -0.6299]]])
result 张量
:tensor([[ 2.6971,  2.2334,  0.8834],
        [-1.0334,  1.2148, -5.6850],
        [ 0.9095, -2.4160,  0.7360]])
torch.Size([3, 3])


##### torch.einsum()


 einsum与tensordot的不同
 1. 从输出结果看出，einsum的结果是特tensordot的特例，（tensordot返回的第一个元素的第一列和第二个元素的第二列是einsum的第一行和第二行，这是因为tensordot循环了所有结果，einsum只循环了指定结果。）

In [9]:
import torch
# 批量矩阵-向量乘法，但只在特定维度
batch = torch.tensor([[[1, 2, 3],
                      [4, 5, 6], 
                      [7, 8, 9],
                      [10, 11, 12],
                      [13, 14, 15]],
                     [[2, 3, 4],
                      [5, 6, 7],
                      [8, 9, 10], 
                      [11, 12, 13],
                      [14, 15, 16]]])  # shape: (2,5,3)
vectors = torch.tensor([[1, 2, 3],
                       [2, 3, 4]])  # shape: (2,3)
# 对每个批次，将最后一个维度相乘
result1 = torch.tensordot(batch, vectors, dims=([2], [1]))

print(result1)
result2 = torch.einsum('bij,bj->bi', batch, vectors)
print(result2)




tensor([[[ 14,  20],
         [ 32,  47],
         [ 50,  74],
         [ 68, 101],
         [ 86, 128]],

        [[ 20,  29],
         [ 38,  56],
         [ 56,  83],
         [ 74, 110],
         [ 92, 137]]])
tensor([[ 14,  32,  50,  68,  86],
        [ 29,  56,  83, 110, 137]])


einsum求和的外积：  
m维向量$\vec{a}$和n维向量$\vec{b}$的外积：
$\vec{a}*\vec{b}^T$  
中的元素为:$c_{ij}=a_i*b_j$,  
用爱因斯坦求和写为："i,j->ij"


In [10]:
# 举例说明外积
a = torch.tensor([1, 2, 3])  # 3维向量
b = torch.tensor([4, 5])     # 2维向量

# 使用einsum计算外积
c = torch.einsum('i,j->ij', a, b)

print("向量a:", a)
print("向量b:", b) 
print("外积结果:")
print(c)
# 结果是一个3x2的矩阵，其中c[i,j] = a[i] * b[j]


向量a: tensor([1, 2, 3])
向量b: tensor([4, 5])
外积结果:
tensor([[ 4,  5],
        [ 8, 10],
        [12, 15]])


##### torch.repeat(*sizes)

In [1]:
import torch

# 创建一个张量
x = torch.tensor([1, 2, 3])

x.repeat(2,3)

tensor([[1, 2, 3, 1, 2, 3, 1, 2, 3],
        [1, 2, 3, 1, 2, 3, 1, 2, 3]])

##### torch.split(tensor, split_size_or_sections, dim=0)
- tensor：要分割的张量
- split_size_or_sections：  
如果是整数，表示每块的大小  
如果是列表或元组，表示每块的具体大小
- dim：在哪个维度上分割，默认是第0维
- 返回的是元组
- 与np.split不同的是np.split的indices_or_sections参数是按按索引列表切分的；

In [5]:
#split_size_or_sections是整数情况
import torch

x = torch.arange(10)
print("原始张量:", x)  # tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# 按3分割
parts = torch.split(x, 3)
print(parts)

原始张量: tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
(tensor([0, 1, 2]), tensor([3, 4, 5]), tensor([6, 7, 8]), tensor([9]))


In [ ]:
#split_size_or_sections是列表情况
import torch
x = torch.arange(10)
parts = torch.split(x, [2, 4, 4])
print(parts)

(tensor([0, 1]), tensor([2, 3, 4, 5]), tensor([6, 7, 8, 9]))


In [4]:
#多维情况，要指定划分维度
import torch
x = torch.arange(12).reshape(3, 4)
print("原始张量:\n", x)
# tensor([[ 0,  1,  2,  3],
#         [ 4,  5,  6,  7],
#         [ 8,  9, 10, 11]])

# 按列分割，每块2列
parts = torch.split(x, 2, dim=1)
print(parts)

原始张量:
 tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
(tensor([[0, 1],
        [4, 5],
        [8, 9]]), tensor([[ 2,  3],
        [ 6,  7],
        [10, 11]]))


##### torch.mul和torch.matmul的区别  
torch.mul是逐元素相乘，torch.matmul是矩阵乘法。










In [1]:
import torch

a = torch.tensor([[1, 2], [3, 4]])
b = torch.tensor([[10, 20], [30, 40]])

result = torch.mul(a, b)
print(result)

tensor([[ 10,  40],
        [ 90, 160]])


In [2]:
import torch

a = torch.tensor([[1, 2], [3, 4]])
b = torch.tensor([[5, 6], [7, 8]])

result = torch.matmul(a, b)
print(result)

tensor([[19, 22],
        [43, 50]])


## 模块

### 遍历一个模块的子模块，参数，缓冲区
- .named_modules() ：
  - 返回一个子模块名称和指向该子模块的引用；（注意第一个返回的是这个模块）
  - 也会返回子模块的子模块
- .named_parameters() ：返回一个参数名称和指向该参数的引用；

In [7]:
import torch
import torch.nn as nn

class sub_module(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(10, 20)
        
    def forward(self, x):
        return self.linear(x)

class MyNet(nn.Module):
    def __init__(self):
        super().__init__()
        self.encoder = nn.Linear(10, 20)   # 子模块
        self.relu = nn.ReLU()
        self.decoder = nn.Linear(20, 5)
        self.sub_module = sub_module()

    def forward(self, x):
        x = self.encoder(x)
        x = self.relu(x)
        x = self.decoder(x)
        return x

mynet = MyNet()

for name, param in mynet.named_parameters():
    print(f"{name}: {param.shape}")

print("--------------------------------")
for name, module in mynet.named_modules():
    print(f"{name}: {module.__class__.__name__}")





encoder.weight: torch.Size([20, 10])
encoder.bias: torch.Size([20])
decoder.weight: torch.Size([5, 20])
decoder.bias: torch.Size([5])
sub_module.linear.weight: torch.Size([20, 10])
sub_module.linear.bias: torch.Size([20])
--------------------------------
: MyNet
encoder: Linear
relu: ReLU
decoder: Linear
sub_module: sub_module
sub_module.linear: Linear
